using static VDStudios.MagicEngine.Input.Constants;

namespace VDStudios.MagicEngine.Input;

/// <summary>
/// Represents a keyboard layout independent code for keyboard keys
/// </summary>
/// <remarks>
/// Modeled after SDL
/// </remarks>
public enum Scancode
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    Unknown = SDL_SCANCODE_UNKNOWN,

    A = SDL_SCANCODE_A,
    B = SDL_SCANCODE_B,
    C = SDL_SCANCODE_C,
    D = SDL_SCANCODE_D,
    E = SDL_SCANCODE_E,
    F = SDL_SCANCODE_F,
    G = SDL_SCANCODE_G,
    H = SDL_SCANCODE_H,
    I = SDL_SCANCODE_I,
    J = SDL_SCANCODE_J,
    K = SDL_SCANCODE_K,
    L = SDL_SCANCODE_L,
    M = SDL_SCANCODE_M,
    N = SDL_SCANCODE_N,
    O = SDL_SCANCODE_O,
    P = SDL_SCANCODE_P,
    Q = SDL_SCANCODE_Q,
    R = SDL_SCANCODE_R,
    S = SDL_SCANCODE_S,
    T = SDL_SCANCODE_T,
    U = SDL_SCANCODE_U,
    V = SDL_SCANCODE_V,
    W = SDL_SCANCODE_W,
    X = SDL_SCANCODE_X,
    Y = SDL_SCANCODE_Y,
    Z = SDL_SCANCODE_Z,

    Num1 = SDL_SCANCODE_1,
    Num2 = SDL_SCANCODE_2,
    Num3 = SDL_SCANCODE_3,
    Num4 = SDL_SCANCODE_4,
    Num5 = SDL_SCANCODE_5,
    Num6 = SDL_SCANCODE_6,
    Num7 = SDL_SCANCODE_7,
    Num8 = SDL_SCANCODE_8,
    Num9 = SDL_SCANCODE_9,
    Num0 = SDL_SCANCODE_0,

    Return = SDL_SCANCODE_RETURN,
    Escape = SDL_SCANCODE_ESCAPE,
    Backspace = SDL_SCANCODE_BACKSPACE,
    Tab = SDL_SCANCODE_TAB,
    Space = SDL_SCANCODE_SPACE,

    Minus = SDL_SCANCODE_MINUS,
    Equals = SDL_SCANCODE_EQUALS,
    LeftBracket = SDL_SCANCODE_LEFTBRACKET,
    RightBracket = SDL_SCANCODE_RIGHTBRACKET,
    Backslash = SDL_SCANCODE_BACKSLASH,
    Nonushash = SDL_SCANCODE_NONUSHASH,
    Semicolon = SDL_SCANCODE_SEMICOLON,
    Apostrophe = SDL_SCANCODE_APOSTROPHE,
    Grave = SDL_SCANCODE_GRAVE,
    Comma = SDL_SCANCODE_COMMA,
    Period = SDL_SCANCODE_PERIOD,
    Slash = SDL_SCANCODE_SLASH,

    Capslock = SDL_SCANCODE_CAPSLOCK,

    F1 = SDL_SCANCODE_F1,
    F2 = SDL_SCANCODE_F2,
    F3 = SDL_SCANCODE_F3,
    F4 = SDL_SCANCODE_F4,
    F5 = SDL_SCANCODE_F5,
    F6 = SDL_SCANCODE_F6,
    F7 = SDL_SCANCODE_F7,
    F8 = SDL_SCANCODE_F8,
    F9 = SDL_SCANCODE_F9,
    F10 = SDL_SCANCODE_F10,
    F11 = SDL_SCANCODE_F11,
    F12 = SDL_SCANCODE_F12,

    Printscreen = SDL_SCANCODE_PRINTSCREEN,
    ScrollLock = SDL_SCANCODE_SCROLLLOCK,
    Pause = SDL_SCANCODE_PAUSE,
    Insert = SDL_SCANCODE_INSERT,
    Home = SDL_SCANCODE_HOME,
    PageUp = SDL_SCANCODE_PAGEUP,
    Delete = SDL_SCANCODE_DELETE,
    End = SDL_SCANCODE_END,
    PageDown = SDL_SCANCODE_PAGEDOWN,
    Right = SDL_SCANCODE_RIGHT,
    Left = SDL_SCANCODE_LEFT,
    Down = SDL_SCANCODE_DOWN,
    Up = SDL_SCANCODE_UP,

    NumlockClear = SDL_SCANCODE_NUMLOCKCLEAR,
    KeyPadDivide = SDL_SCANCODE_KP_DIVIDE,
    KeyPadMultiply = SDL_SCANCODE_KP_MULTIPLY,
    KeyPadMinus = SDL_SCANCODE_KP_MINUS,
    KeyPadPlus = SDL_SCANCODE_KP_PLUS,
    KeyPadEnter = SDL_SCANCODE_KP_ENTER,
    KeyPad1 = SDL_SCANCODE_KP_1,
    KeyPad2 = SDL_SCANCODE_KP_2,
    KeyPad3 = SDL_SCANCODE_KP_3,
    KeyPad4 = SDL_SCANCODE_KP_4,
    KeyPad5 = SDL_SCANCODE_KP_5,
    KeyPad6 = SDL_SCANCODE_KP_6,
    KeyPad7 = SDL_SCANCODE_KP_7,
    KeyPad8 = SDL_SCANCODE_KP_8,
    KeyPad9 = SDL_SCANCODE_KP_9,
    KeyPad0 = SDL_SCANCODE_KP_0,
    KeyPadPeriod = SDL_SCANCODE_KP_PERIOD,

    Nonusbackslash = SDL_SCANCODE_NONUSBACKSLASH,
    Application = SDL_SCANCODE_APPLICATION,
    Power = SDL_SCANCODE_POWER,
    KeyPadEquals = SDL_SCANCODE_KP_EQUALS,
    F13 = SDL_SCANCODE_F13,
    F14 = SDL_SCANCODE_F14,
    F15 = SDL_SCANCODE_F15,
    F16 = SDL_SCANCODE_F16,
    F17 = SDL_SCANCODE_F17,
    F18 = SDL_SCANCODE_F18,
    F19 = SDL_SCANCODE_F19,
    F20 = SDL_SCANCODE_F20,
    F21 = SDL_SCANCODE_F21,
    F22 = SDL_SCANCODE_F22,
    F23 = SDL_SCANCODE_F23,
    F24 = SDL_SCANCODE_F24,
    Execute = SDL_SCANCODE_EXECUTE,
    Help = SDL_SCANCODE_HELP,
    Menu = SDL_SCANCODE_MENU,
    Select = SDL_SCANCODE_SELECT,
    Stop = SDL_SCANCODE_STOP,
    Again = SDL_SCANCODE_AGAIN,
    Undo = SDL_SCANCODE_UNDO,
    Cut = SDL_SCANCODE_CUT,
    Copy = SDL_SCANCODE_COPY,
    Paste = SDL_SCANCODE_PASTE,
    Find = SDL_SCANCODE_FIND,
    Mute = SDL_SCANCODE_MUTE,
    Volumeup = SDL_SCANCODE_VOLUMEUP,
    Volumedown = SDL_SCANCODE_VOLUMEDOWN,
    KeyPadComma = SDL_SCANCODE_KP_COMMA,
    KeyPadEqualSAS400 = SDL_SCANCODE_KP_EQUALSAS400,

    International1 = SDL_SCANCODE_INTERNATIONAL1,
    International2 = SDL_SCANCODE_INTERNATIONAL2,
    International3 = SDL_SCANCODE_INTERNATIONAL3,
    International4 = SDL_SCANCODE_INTERNATIONAL4,
    International5 = SDL_SCANCODE_INTERNATIONAL5,
    International6 = SDL_SCANCODE_INTERNATIONAL6,
    International7 = SDL_SCANCODE_INTERNATIONAL7,
    International8 = SDL_SCANCODE_INTERNATIONAL8,
    International9 = SDL_SCANCODE_INTERNATIONAL9,
    Lang1 = SDL_SCANCODE_LANG1,
    Lang2 = SDL_SCANCODE_LANG2,
    Lang3 = SDL_SCANCODE_LANG3,
    Lang4 = SDL_SCANCODE_LANG4,
    Lang5 = SDL_SCANCODE_LANG5,
    Lang6 = SDL_SCANCODE_LANG6,
    Lang7 = SDL_SCANCODE_LANG7,
    Lang8 = SDL_SCANCODE_LANG8,
    Lang9 = SDL_SCANCODE_LANG9,

    Alterase = SDL_SCANCODE_ALTERASE,
    Sysreq = SDL_SCANCODE_SYSREQ,
    Cancel = SDL_SCANCODE_CANCEL,
    Clear = SDL_SCANCODE_CLEAR,
    Prior = SDL_SCANCODE_PRIOR,
    Return2 = SDL_SCANCODE_RETURN2,
    Separator = SDL_SCANCODE_SEPARATOR,
    Out = SDL_SCANCODE_OUT,
    Oper = SDL_SCANCODE_OPER,
    ClearAgain = SDL_SCANCODE_CLEARAGAIN,
    Crsel = SDL_SCANCODE_CRSEL,
    Exsel = SDL_SCANCODE_EXSEL,

    KeyPad00 = SDL_SCANCODE_KP_00,
    KeyPad000 = SDL_SCANCODE_KP_000,
    ThousandsSeparator = SDL_SCANCODE_THOUSANDSSEPARATOR,
    DecimalSeparator = SDL_SCANCODE_DECIMALSEPARATOR,
    CurrencyUnit = SDL_SCANCODE_CURRENCYUNIT,
    CurrencySubUnit = SDL_SCANCODE_CURRENCYSUBUNIT,
    KeyPadLeftParentheses = SDL_SCANCODE_KP_LEFTPAREN,
    KeyPadRightParentheses = SDL_SCANCODE_KP_RIGHTPAREN,
    KeyPadLeftBrace = SDL_SCANCODE_KP_LEFTBRACE,
    KeyPadRightBrace = SDL_SCANCODE_KP_RIGHTBRACE,
    KeyPadTab = SDL_SCANCODE_KP_TAB,
    KeyPadBackspace = SDL_SCANCODE_KP_BACKSPACE,
    KeyPadA = SDL_SCANCODE_KP_A,
    KeyPadB = SDL_SCANCODE_KP_B,
    KeyPadC = SDL_SCANCODE_KP_C,
    KeyPadD = SDL_SCANCODE_KP_D,
    KeyPadE = SDL_SCANCODE_KP_E,
    KeyPadF = SDL_SCANCODE_KP_F,
    KeyPadXor = SDL_SCANCODE_KP_XOR,
    KeyPadPower = SDL_SCANCODE_KP_POWER,
    KeyPadPercent = SDL_SCANCODE_KP_PERCENT,
    KeyPadLessThan = SDL_SCANCODE_KP_LESS,
    KeyPadGreaterThan = SDL_SCANCODE_KP_GREATER,
    KeyPadAmpersand = SDL_SCANCODE_KP_AMPERSAND,
    KeyPadDoubleAmpersand = SDL_SCANCODE_KP_DBLAMPERSAND,
    KeyPadVerticalBar = SDL_SCANCODE_KP_VERTICALBAR,
    KeyPadDoubleVerticalBar = SDL_SCANCODE_KP_DBLVERTICALBAR,
    KeyPadColon = SDL_SCANCODE_KP_COLON,
    KeyPadHash = SDL_SCANCODE_KP_HASH,
    KeyPadSpace = SDL_SCANCODE_KP_SPACE,
    KeyPadAt = SDL_SCANCODE_KP_AT,
    KeyPadExclam = SDL_SCANCODE_KP_EXCLAM,
    KeyPadMemoryStore = SDL_SCANCODE_KP_MEMSTORE,
    KeyPadMemoryRecall = SDL_SCANCODE_KP_MEMRECALL,
    KeyPadMemoryClear = SDL_SCANCODE_KP_MEMCLEAR,
    KeyPadMemoryAdd = SDL_SCANCODE_KP_MEMADD,
    KeyPadMemorySubtract = SDL_SCANCODE_KP_MEMSUBTRACT,
    KeyPadMemoryMultiply = SDL_SCANCODE_KP_MEMMULTIPLY,
    KeyPadMemoryDivide = SDL_SCANCODE_KP_MEMDIVIDE,
    KeyPadPlusMinus = SDL_SCANCODE_KP_PLUSMINUS,
    KeyPadClear = SDL_SCANCODE_KP_CLEAR,
    KeyPadClearEntry = SDL_SCANCODE_KP_CLEARENTRY,
    KeyPadBinary = SDL_SCANCODE_KP_BINARY,
    KeyPadOctal = SDL_SCANCODE_KP_OCTAL,
    KeyPadDecimal = SDL_SCANCODE_KP_DECIMAL,
    KeyPadHexadecimal = SDL_SCANCODE_KP_HEXADECIMAL,

    LeftCtrl = SDL_SCANCODE_LCTRL,
    LeftShift = SDL_SCANCODE_LSHIFT,
    LeftAlt = SDL_SCANCODE_LALT,

    /// <summary>
    /// Windows key, Command in Mac, etc.
    /// </summary>
    LeftGUI = SDL_SCANCODE_LGUI,
    RightCtrl = SDL_SCANCODE_RCTRL,
    RightShift = SDL_SCANCODE_RSHIFT,
    RightAlt = SDL_SCANCODE_RALT,

    /// <summary>
    /// Windows key, Command in Mac, etc.
    /// </summary>
    RightGUI = SDL_SCANCODE_RGUI,

    Mode = SDL_SCANCODE_MODE,

    /* These come from the USB consumer page (0x0C) */
    AudioNext = SDL_SCANCODE_AUDIONEXT,
    AudioPrev = SDL_SCANCODE_AUDIOPREV,
    AudioStop = SDL_SCANCODE_AUDIOSTOP,
    AudioPlay = SDL_SCANCODE_AUDIOPLAY,
    AudioMute = SDL_SCANCODE_AUDIOMUTE,
    MediaSelect = SDL_SCANCODE_MEDIASELECT,
    WWW = SDL_SCANCODE_WWW,
    Mail = SDL_SCANCODE_MAIL,
    Calculator = SDL_SCANCODE_CALCULATOR,
    Computer = SDL_SCANCODE_COMPUTER,
    AppControlSearch = SDL_SCANCODE_AC_SEARCH,
    AppControlHome = SDL_SCANCODE_AC_HOME,
    AppControlBack = SDL_SCANCODE_AC_BACK,
    AppControlForward = SDL_SCANCODE_AC_FORWARD,
    AppControlStop = SDL_SCANCODE_AC_STOP,
    AppControlRefresh = SDL_SCANCODE_AC_REFRESH,
    AppControlBookmarks = SDL_SCANCODE_AC_BOOKMARKS,

    /* These come from other sources, and are mostly mac related */
    BrightnessDown = SDL_SCANCODE_BRIGHTNESSDOWN,
    BrightnessUp = SDL_SCANCODE_BRIGHTNESSUP,
    DisplaySwitch = SDL_SCANCODE_DISPLAYSWITCH,
    KeyboardIlluminationToggle = SDL_SCANCODE_KBDILLUMTOGGLE,
    KeyboardIlluminationDown = SDL_SCANCODE_KBDILLUMDOWN,
    KeyboardIlluminationUp = SDL_SCANCODE_KBDILLUMUP,
    Eject = SDL_SCANCODE_EJECT,
    Sleep = SDL_SCANCODE_SLEEP,

    App1 = SDL_SCANCODE_APP1,
    App2 = SDL_SCANCODE_APP2,

    /* These come from the USB consumer page (0x0C) */
    AudioRewind = SDL_SCANCODE_AUDIOREWIND,
    AudioFastForward = SDL_SCANCODE_AUDIOFASTFORWARD,
}
