//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDStudios.MagicEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BuiltInResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuiltInResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VDStudios.MagicEngine.Properties.BuiltInResources", typeof(BuiltInResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 450
        ///
        ///layout(location = 0) out vec4 outColor;
        ///
        ///void main() {
        ///    outColor = vec4(1.0, 50.0, 1.0, 0.5);
        ///}.
        /// </summary>
        public static string DefaultPolygonFragmentShader {
            get {
                return ResourceManager.GetString("DefaultPolygonFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 450
        ///
        ///layout(location = 0) in vec2 Position;
        ///
        ///void main() {
        ///    gl_Position = vec4(Position, 0.0, 1.0);
        ///}.
        /// </summary>
        public static string DefaultPolygonVertexShader {
            get {
                return ResourceManager.GetString("DefaultPolygonVertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 450
        ///
        ///layout(location = 0) out vec4 outColor;
        ///layout(set = 0, binding = 0) uniform sampler2D sampler;
        ///layout(set = 0, binding = 1) uniform texture2D tex;
        ///
        ///void main() {
        ///    outColor = texture(tex, sampler);
        ///}.
        /// </summary>
        public static string DefaultTexturePolygonFragmentShader {
            get {
                return ResourceManager.GetString("DefaultTexturePolygonFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 450
        ///
        ///layout(location = 0) in vec2 Position;
        ///
        ///void main() {
        ///    gl_Position = vec4(Position, 0.0, 1.0);
        ///}.
        /// </summary>
        public static string DefaultTexturePolygonVertexShader {
            get {
                return ResourceManager.GetString("DefaultTexturePolygonVertexShader", resourceCulture);
            }
        }
    }
}
